// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// Auth implements auth operation.
	//
	// OIDC Authorization.
	//
	// GET /auth
	Auth(ctx context.Context) (AuthRes, error)
	// Callback implements callback operation.
	//
	// OIDC Callback.
	//
	// GET /callback
	Callback(ctx context.Context, params CallbackParams) (CallbackRes, error)
	// Get implements GET / operation.
	//
	// Login.
	//
	// GET /
	Get(ctx context.Context) (GetOK, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
